BEGIN;

SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '15min';

ALTER TABLE public.jobs
    ADD COLUMN IF NOT EXISTS same_id_relist_count integer NOT NULL DEFAULT 0;

COMMENT ON COLUMN public.jobs.same_id_relist_count IS
    'Conservative lower bound for accepted same-ID relist events: the listing was relisted at least once when greater than zero.';

CREATE TABLE IF NOT EXISTS public.ingestion_runs (
    id uuid PRIMARY KEY,
    provider text NOT NULL,
    search_query text,
    archetype text,
    filter_profile text,
    query_scope text NOT NULL DEFAULT '',
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    finished_at timestamp with time zone,
    status text NOT NULL DEFAULT 'running',
    pages_attempted integer NOT NULL DEFAULT 0 CHECK (pages_attempted >= 0),
    pages_completed integer NOT NULL DEFAULT 0 CHECK (pages_completed >= 0),
    cards_seen integer NOT NULL DEFAULT 0 CHECK (cards_seen >= 0),
    detail_budget_used integer NOT NULL DEFAULT 0 CHECK (detail_budget_used >= 0),
    coverage_complete boolean NOT NULL DEFAULT false,
    coverage_reason text,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.ingestion_runs ADD COLUMN IF NOT EXISTS query_scope text NOT NULL DEFAULT '';
UPDATE public.ingestion_runs
SET pages_completed = LEAST(pages_completed, pages_attempted),
    status = CASE WHEN status IN ('running', 'complete', 'incomplete', 'failed') THEN status ELSE 'failed' END;
ALTER TABLE public.ingestion_runs DROP CONSTRAINT IF EXISTS ingestion_runs_status_check;
ALTER TABLE public.ingestion_runs ADD CONSTRAINT ingestion_runs_status_check
    CHECK (status IN ('running', 'complete', 'incomplete', 'failed'));
ALTER TABLE public.ingestion_runs DROP CONSTRAINT IF EXISTS ingestion_runs_page_coverage_check;
ALTER TABLE public.ingestion_runs ADD CONSTRAINT ingestion_runs_page_coverage_check
    CHECK (pages_completed <= pages_attempted);

CREATE TABLE IF NOT EXISTS public.listing_observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL,
    source_job_id text NOT NULL,
    canonical_job_id text REFERENCES public.jobs(job_id) ON DELETE SET NULL,
    ingestion_run_id uuid NOT NULL REFERENCES public.ingestion_runs(id) ON DELETE RESTRICT,
    observed_at timestamp with time zone NOT NULL DEFAULT now(),
    posted_at date,
    posted_relative_text text,
    location text,
    card_label text,
    result text NOT NULL DEFAULT 'seen',
    query_scope text,
    parser_version text NOT NULL DEFAULT 'linkedin-guest-card-v1',
    trigger_evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    first_seen_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT listing_observations_idempotency
        UNIQUE (provider, source_job_id, ingestion_run_id, query_scope, result)
);

ALTER TABLE public.listing_observations DROP CONSTRAINT IF EXISTS listing_observations_idempotency;
UPDATE public.listing_observations SET query_scope = '' WHERE query_scope IS NULL;
ALTER TABLE public.listing_observations ALTER COLUMN query_scope SET DEFAULT '';
ALTER TABLE public.listing_observations ALTER COLUMN query_scope SET NOT NULL;
ALTER TABLE public.listing_observations ADD CONSTRAINT listing_observations_idempotency
    UNIQUE (provider, source_job_id, ingestion_run_id, query_scope, result);

CREATE TABLE IF NOT EXISTS public.listing_content_versions (
    provider text NOT NULL,
    source_job_id text NOT NULL,
    content_hash text NOT NULL,
    canonical_job_id text REFERENCES public.jobs(job_id) ON DELETE SET NULL,
    description text NOT NULL,
    description_fingerprint text,
    hash_algorithm_version text NOT NULL DEFAULT 'description-sha256-v1',
    fingerprint_algorithm_version text NOT NULL DEFAULT 'description-fingerprint-v1',
    first_observed_at timestamp with time zone NOT NULL DEFAULT now(),
    last_observed_at timestamp with time zone NOT NULL DEFAULT now(),
    last_ingestion_run_id uuid REFERENCES public.ingestion_runs(id) ON DELETE SET NULL,
    observation_count integer NOT NULL DEFAULT 1 CHECK (observation_count >= 1),
    PRIMARY KEY (provider, source_job_id, content_hash)
);

CREATE TABLE IF NOT EXISTS public.listing_relist_events (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    provider text NOT NULL,
    source_job_id text NOT NULL,
    canonical_job_id text REFERENCES public.jobs(job_id) ON DELETE SET NULL,
    relisted_on date NOT NULL,
    observed_at timestamp with time zone NOT NULL,
    ingestion_run_id uuid REFERENCES public.ingestion_runs(id) ON DELETE SET NULL,
    confidence text NOT NULL DEFAULT 'conservative',
    algorithm_version text NOT NULL DEFAULT 'same-id-relist-v1',
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    superseded_by uuid REFERENCES public.listing_relist_events(id) ON DELETE RESTRICT,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT listing_relist_events_idempotency
        UNIQUE (provider, source_job_id, relisted_on)
);

CREATE TABLE IF NOT EXISTS public.listing_states (
    provider text NOT NULL,
    source_job_id text NOT NULL,
    canonical_job_id text REFERENCES public.jobs(job_id) ON DELETE SET NULL,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    latest_trusted_posted_date date,
    current_content_hash text,
    same_id_relist_count integer NOT NULL DEFAULT 0 CHECK (same_id_relist_count >= 0),
    source_state text NOT NULL DEFAULT 'observed',
    pending_relist_on date,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (provider, source_job_id)
);
ALTER TABLE public.listing_states ADD COLUMN IF NOT EXISTS pending_relist_on date;

CREATE INDEX IF NOT EXISTS idx_listing_observations_source_job_id
    ON public.listing_observations (source_job_id);
CREATE INDEX IF NOT EXISTS idx_listing_observations_canonical_job_id
    ON public.listing_observations (canonical_job_id);
CREATE INDEX IF NOT EXISTS idx_listing_observations_replay
    ON public.listing_observations (provider, source_job_id, observed_at, ingestion_run_id);
CREATE INDEX IF NOT EXISTS idx_listing_observations_run_scope
    ON public.listing_observations (ingestion_run_id, query_scope);
CREATE INDEX IF NOT EXISTS idx_listing_relist_events_source_date
    ON public.listing_relist_events (provider, source_job_id, relisted_on);
CREATE INDEX IF NOT EXISTS idx_ingestion_runs_provider_started
    ON public.ingestion_runs (provider, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_listing_content_versions_canonical_job_id
    ON public.listing_content_versions (canonical_job_id);
CREATE INDEX IF NOT EXISTS idx_listing_relist_events_canonical_job_id
    ON public.listing_relist_events (canonical_job_id);
CREATE INDEX IF NOT EXISTS idx_listing_states_canonical_job_id
    ON public.listing_states (canonical_job_id);

CREATE OR REPLACE FUNCTION public.prevent_listing_observation_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
    RAISE EXCEPTION 'listing_observations is append-only';
END;
$$;

DROP TRIGGER IF EXISTS listing_observations_append_only ON public.listing_observations;
CREATE TRIGGER listing_observations_append_only
    BEFORE UPDATE OR DELETE ON public.listing_observations
    FOR EACH ROW EXECUTE FUNCTION public.prevent_listing_observation_mutation();

ALTER TABLE public.ingestion_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_content_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_relist_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_states ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.ingestion_runs FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.listing_observations FROM PUBLIC, anon, authenticated;
REVOKE UPDATE, DELETE ON TABLE public.listing_observations FROM service_role;
REVOKE ALL ON TABLE public.listing_content_versions FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.listing_relist_events FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.listing_states FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.ingestion_runs TO service_role;
GRANT SELECT, INSERT ON TABLE public.listing_observations TO service_role;
GRANT ALL ON TABLE public.listing_content_versions TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.listing_relist_events TO service_role;
GRANT ALL ON TABLE public.listing_states TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE OR REPLACE FUNCTION public.apply_linkedin_relist_projection(
    p_canonical_job_id text,
    p_source_job_id text,
    p_ingestion_run_id uuid,
    p_relisted_on date,
    p_observed_at timestamptz,
    p_projection jsonb,
    p_expected_listing_instances jsonb,
    p_expected_last_seen_at timestamptz,
    p_evidence jsonb,
    p_description text,
    p_content_hash text,
    p_description_fingerprint text
) RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    affected integer;
BEGIN
    IF p_relisted_on IS NULL OR p_content_hash IS NULL OR p_description IS NULL THEN
        RETURN false;
    END IF;
    UPDATE public.jobs
    SET listing_instances = p_projection->'listing_instances',
        seen_count = (p_projection->>'seen_count')::integer,
        posting_wave_count = (p_projection->>'posting_wave_count')::integer,
        repost_count = (p_projection->>'repost_count')::integer,
        same_id_relist_count = (p_projection->>'same_id_relist_count')::integer,
        latest_job_id = p_projection->>'latest_job_id',
        last_seen_at = (p_projection->>'last_seen_at')::timestamptz,
        last_seen_posted_at = NULLIF(p_projection->>'last_seen_posted_at', '')::timestamptz,
        description = COALESCE(p_projection->>'description', description),
        description_fingerprint = COALESCE(p_projection->>'description_fingerprint', description_fingerprint),
        is_active = COALESCE((p_projection->>'is_active')::boolean, is_active),
        job_state = COALESCE(p_projection->>'job_state', job_state)
    WHERE job_id = p_canonical_job_id
      AND listing_instances = p_expected_listing_instances
      AND last_seen_at IS NOT DISTINCT FROM p_expected_last_seen_at;
    GET DIAGNOSTICS affected = ROW_COUNT;
    IF affected <> 1 THEN
        RETURN false;
    END IF;

    INSERT INTO public.listing_relist_events (
        provider, source_job_id, canonical_job_id, relisted_on, observed_at,
        ingestion_run_id, evidence
    ) VALUES (
        'linkedin', p_source_job_id, p_canonical_job_id, p_relisted_on,
        p_observed_at, p_ingestion_run_id, COALESCE(p_evidence, '{}'::jsonb)
    ) ON CONFLICT (provider, source_job_id, relisted_on) DO NOTHING;

    INSERT INTO public.listing_content_versions (
        provider, source_job_id, content_hash, canonical_job_id, description,
        description_fingerprint, first_observed_at, last_observed_at,
        observation_count, last_ingestion_run_id
    ) VALUES (
        'linkedin', p_source_job_id, p_content_hash, p_canonical_job_id,
        p_description, p_description_fingerprint, p_observed_at, p_observed_at,
        1, p_ingestion_run_id
    ) ON CONFLICT (provider, source_job_id, content_hash) DO UPDATE SET
        canonical_job_id = EXCLUDED.canonical_job_id,
        description = EXCLUDED.description,
        description_fingerprint = EXCLUDED.description_fingerprint,
        last_observed_at = GREATEST(listing_content_versions.last_observed_at, EXCLUDED.last_observed_at),
        last_ingestion_run_id = EXCLUDED.last_ingestion_run_id,
        observation_count = CASE
            WHEN listing_content_versions.last_ingestion_run_id IS DISTINCT FROM EXCLUDED.last_ingestion_run_id
            THEN listing_content_versions.observation_count + 1
            ELSE listing_content_versions.observation_count
        END;

    INSERT INTO public.listing_states (
        provider, source_job_id, canonical_job_id, first_seen_at, last_seen_at,
        latest_trusted_posted_date, current_content_hash, same_id_relist_count
    ) VALUES (
        'linkedin', p_source_job_id, p_canonical_job_id, p_observed_at,
        p_observed_at, p_relisted_on, p_content_hash,
        (p_projection->>'same_id_relist_count')::integer
    ) ON CONFLICT (provider, source_job_id) DO UPDATE SET
        canonical_job_id = EXCLUDED.canonical_job_id,
        last_seen_at = EXCLUDED.last_seen_at,
        latest_trusted_posted_date = EXCLUDED.latest_trusted_posted_date,
        current_content_hash = EXCLUDED.current_content_hash,
        same_id_relist_count = GREATEST(listing_states.same_id_relist_count, EXCLUDED.same_id_relist_count),
        updated_at = now();

    UPDATE public.listing_states
    SET pending_relist_on = NULL,
        same_id_relist_count = GREATEST(
            same_id_relist_count,
            (p_projection->>'same_id_relist_count')::integer
        ),
        current_content_hash = p_content_hash,
        updated_at = now()
    WHERE provider = 'linkedin'
      AND source_job_id = p_source_job_id
      AND pending_relist_on = p_relisted_on;

    RETURN true;
END;
$$;
REVOKE ALL ON FUNCTION public.apply_linkedin_relist_projection(text, text, uuid, date, timestamptz, jsonb, jsonb, timestamptz, jsonb, text, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_linkedin_relist_projection(text, text, uuid, date, timestamptz, jsonb, jsonb, timestamptz, jsonb, text, text, text) TO service_role;

-- Seed only directly evidenced historical facts. Re-running this migration is safe.
INSERT INTO public.listing_content_versions (
    provider, source_job_id, content_hash, canonical_job_id, description,
    description_fingerprint, first_observed_at, last_observed_at
)
SELECT
    'linkedin', COALESCE(NULLIF(j.latest_job_id, ''), j.job_id),
    encode(extensions.digest(replace(replace(trim(j.description), E'\r\n', E'\n'), E'\r', E'\n'), 'sha256'), 'hex'),
    j.job_id, j.description, j.description_fingerprint,
    COALESCE(j.first_seen_at, j.scraped_at, now()),
    COALESCE(j.last_seen_at, j.scraped_at, now())
FROM public.jobs j
WHERE j.provider = 'linkedin' AND j.description IS NOT NULL
ON CONFLICT (provider, source_job_id, content_hash) DO NOTHING;

WITH instances AS (
    SELECT
        j.job_id AS canonical_job_id,
        instance->>'job_id' AS source_job_id,
        NULLIF(instance->>'posted_at', '')::date AS relisted_on,
        COALESCE(NULLIF(instance->>'last_seen_at', '')::timestamptz, j.last_seen_at, j.scraped_at, now()) AS observed_at,
        min(NULLIF(instance->>'posted_at', '')::date) OVER (
            PARTITION BY j.job_id, instance->>'job_id'
        ) AS first_posted_on
    FROM public.jobs j
    CROSS JOIN LATERAL jsonb_array_elements(COALESCE(j.listing_instances, '[]'::jsonb)) instance
    WHERE j.provider = 'linkedin'
      AND instance->>'job_id' IS NOT NULL
      AND NULLIF(instance->>'posted_at', '') IS NOT NULL
)
INSERT INTO public.listing_relist_events (
    provider, source_job_id, canonical_job_id, relisted_on, observed_at, evidence
)
SELECT
    'linkedin', source_job_id, canonical_job_id, relisted_on, observed_at,
    jsonb_build_object('source', 'historical_listing_instances_seed', 'lower_bound', true)
FROM instances
WHERE relisted_on > first_posted_on
    ON CONFLICT (provider, source_job_id, relisted_on) DO NOTHING;

COMMIT;
