BEGIN;

SET LOCAL statement_timeout = '15min';
SET LOCAL lock_timeout = '10s';
SET LOCAL idle_in_transaction_session_timeout = '5min';
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."jobs" (
    "job_id" "text" NOT NULL,
    "company" "text",
    "job_title" "text",
    "level" "text",
    "location" "text",
    "description" "text",
    "status" "text" DEFAULT 'new'::"text",
    "is_active" boolean DEFAULT true,
    "application_date" timestamp with time zone,
    "resume_score" smallint,
    "notes" "text",
    "scraped_at" timestamp with time zone DEFAULT "now"(),
    "last_checked" timestamp with time zone DEFAULT "now"(),
    "job_state" "text" DEFAULT 'new'::"text",
    "resume_score_stage" "text" DEFAULT 'initial'::"text" NOT NULL,
    "is_interested" boolean,
    "customized_resume_id" "uuid",
    "provider" "text",
    "posted_at" timestamp with time zone,
    "insights_analyzed_at" timestamp with time zone,
    "insights_reanalyzed_at" timestamp with time zone,
    "is_filtered" boolean DEFAULT false,
    "filter_reason" "text",
    "is_entry_level_filtered" boolean DEFAULT false
);


ALTER TABLE "public"."jobs" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."ingestion_runs" (
    "id" uuid PRIMARY KEY,
    "provider" text NOT NULL,
    "search_query" text,
    "archetype" text,
    "filter_profile" text,
    "query_scope" text NOT NULL DEFAULT '',
    "started_at" timestamp with time zone NOT NULL DEFAULT now(),
    "finished_at" timestamp with time zone,
    "status" text NOT NULL DEFAULT 'running' CHECK ("status" IN ('running', 'complete', 'incomplete', 'failed')),
    "pages_attempted" integer NOT NULL DEFAULT 0 CHECK ("pages_attempted" >= 0),
    "pages_completed" integer NOT NULL DEFAULT 0 CHECK ("pages_completed" >= 0),
    "cards_seen" integer NOT NULL DEFAULT 0 CHECK ("cards_seen" >= 0),
    "detail_budget_used" integer NOT NULL DEFAULT 0 CHECK ("detail_budget_used" >= 0),
    "coverage_complete" boolean NOT NULL DEFAULT false,
    "coverage_reason" text,
    CHECK ("pages_completed" <= "pages_attempted"),
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "public"."scrape_run_state" (
    "id" integer PRIMARY KEY CHECK ("id" = 1),
    "last_successful_scrape_at" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS "public"."listing_observations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "provider" text NOT NULL,
    "source_job_id" text NOT NULL,
    "canonical_job_id" text,
    "ingestion_run_id" uuid NOT NULL,
    "observed_at" timestamp with time zone NOT NULL DEFAULT now(),
    "posted_at" date,
    "posted_relative_text" text,
    "location" text,
    "card_label" text,
    "result" text NOT NULL DEFAULT 'seen',
    "query_scope" text NOT NULL DEFAULT '',
    "parser_version" text NOT NULL DEFAULT 'linkedin-guest-card-v1',
    "trigger_evidence" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "first_seen_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "listing_observations_idempotency" UNIQUE ("provider", "source_job_id", "ingestion_run_id", "query_scope", "result")
);
UPDATE "public"."listing_observations" SET "query_scope" = '' WHERE "query_scope" IS NULL;
ALTER TABLE "public"."listing_observations" ALTER COLUMN "query_scope" SET DEFAULT '';
ALTER TABLE "public"."listing_observations" ALTER COLUMN "query_scope" SET NOT NULL;
ALTER TABLE "public"."listing_observations" DROP CONSTRAINT IF EXISTS "listing_observations_idempotency";
ALTER TABLE "public"."listing_observations" ADD CONSTRAINT "listing_observations_idempotency"
    UNIQUE ("provider", "source_job_id", "ingestion_run_id", "query_scope", "result");

CREATE TABLE IF NOT EXISTS "public"."listing_content_versions" (
    "provider" text NOT NULL,
    "source_job_id" text NOT NULL,
    "content_hash" text NOT NULL,
    "canonical_job_id" text,
    "description" text NOT NULL,
    "description_fingerprint" text,
    "hash_algorithm_version" text NOT NULL DEFAULT 'description-sha256-v1',
    "fingerprint_algorithm_version" text NOT NULL DEFAULT 'description-fingerprint-v1',
    "first_observed_at" timestamp with time zone NOT NULL DEFAULT now(),
    "last_observed_at" timestamp with time zone NOT NULL DEFAULT now(),
    "last_ingestion_run_id" uuid,
    "observation_count" integer NOT NULL DEFAULT 1 CHECK ("observation_count" >= 1),
    PRIMARY KEY ("provider", "source_job_id", "content_hash")
);

CREATE TABLE IF NOT EXISTS "public"."listing_relist_events" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "provider" text NOT NULL,
    "source_job_id" text NOT NULL,
    "canonical_job_id" text,
    "relisted_on" date NOT NULL,
    "observed_at" timestamp with time zone NOT NULL,
    "ingestion_run_id" uuid,
    "confidence" text NOT NULL DEFAULT 'conservative',
    "algorithm_version" text NOT NULL DEFAULT 'same-id-relist-v1',
    "evidence" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "superseded_by" uuid,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "listing_relist_events_idempotency" UNIQUE ("provider", "source_job_id", "relisted_on")
);

CREATE TABLE IF NOT EXISTS "public"."listing_states" (
    "provider" text NOT NULL,
    "source_job_id" text NOT NULL,
    "canonical_job_id" text,
    "first_seen_at" timestamp with time zone NOT NULL,
    "last_seen_at" timestamp with time zone NOT NULL,
    "latest_trusted_posted_date" date,
    "current_content_hash" text,
    "same_id_relist_count" integer NOT NULL DEFAULT 0 CHECK ("same_id_relist_count" >= 0),
    "source_state" text NOT NULL DEFAULT 'observed',
    "pending_relist_on" date,
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY ("provider", "source_job_id")
);

CREATE INDEX IF NOT EXISTS "idx_listing_observations_source_job_id" ON "public"."listing_observations" ("source_job_id");
CREATE INDEX IF NOT EXISTS "idx_listing_observations_canonical_job_id" ON "public"."listing_observations" ("canonical_job_id");
CREATE INDEX IF NOT EXISTS "idx_listing_observations_replay" ON "public"."listing_observations" ("provider", "source_job_id", "observed_at", "ingestion_run_id");
CREATE INDEX IF NOT EXISTS "idx_listing_content_versions_canonical_job_id" ON "public"."listing_content_versions" ("canonical_job_id");
CREATE INDEX IF NOT EXISTS "idx_listing_relist_events_canonical_job_id" ON "public"."listing_relist_events" ("canonical_job_id");
CREATE INDEX IF NOT EXISTS "idx_listing_states_canonical_job_id" ON "public"."listing_states" ("canonical_job_id");

CREATE OR REPLACE FUNCTION "public"."prevent_listing_observation_mutation"() RETURNS trigger
    LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
BEGIN
    RAISE EXCEPTION 'listing_observations is append-only';
END;
$$;

CREATE OR REPLACE FUNCTION "public"."record_scrape_success"("p_finished_at" timestamp with time zone)
RETURNS timestamp with time zone
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path = pg_catalog
AS $$
DECLARE
    persisted_at timestamp with time zone;
BEGIN
    IF p_finished_at IS NULL THEN
        RAISE EXCEPTION 'p_finished_at must not be null' USING ERRCODE = '22004';
    END IF;

    INSERT INTO public.scrape_run_state (id, last_successful_scrape_at)
    VALUES (1, p_finished_at)
    ON CONFLICT (id) DO UPDATE
    SET last_successful_scrape_at = EXCLUDED.last_successful_scrape_at
    RETURNING last_successful_scrape_at INTO persisted_at;

    RETURN persisted_at;
END;
$$;

DROP TRIGGER IF EXISTS "listing_observations_append_only" ON "public"."listing_observations";
CREATE TRIGGER "listing_observations_append_only" BEFORE UPDATE OR DELETE ON "public"."listing_observations"
    FOR EACH ROW EXECUTE FUNCTION "public"."prevent_listing_observation_mutation"();

ALTER TABLE "public"."ingestion_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."scrape_run_state" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."listing_observations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."listing_content_versions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."listing_relist_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."listing_states" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_singleton_watermark_access" ON "public"."scrape_run_state";
CREATE POLICY "service_role_singleton_watermark_access"
    ON "public"."scrape_run_state"
    FOR ALL
    TO service_role
    USING ("id" = 1)
    WITH CHECK ("id" = 1);

REVOKE ALL ON TABLE "public"."ingestion_runs" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE "public"."scrape_run_state" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE "public"."listing_observations" FROM PUBLIC, anon, authenticated;
REVOKE UPDATE, DELETE ON TABLE "public"."listing_observations" FROM service_role;
REVOKE ALL ON TABLE "public"."listing_content_versions" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE "public"."listing_relist_events" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE "public"."listing_states" FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE "public"."ingestion_runs" TO service_role;
GRANT ALL ON TABLE "public"."scrape_run_state" TO service_role;
GRANT SELECT, INSERT ON TABLE "public"."listing_observations" TO service_role;
GRANT ALL ON TABLE "public"."listing_content_versions" TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE "public"."listing_relist_events" TO service_role;
GRANT ALL ON TABLE "public"."listing_states" TO service_role;

REVOKE ALL ON FUNCTION "public"."record_scrape_success"(timestamp with time zone) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION "public"."record_scrape_success"(timestamp with time zone) TO service_role;

INSERT INTO "public"."scrape_run_state" ("id")
VALUES (1)
ON CONFLICT ("id") DO NOTHING;


-- Migration: add job filter columns
ALTER TABLE "public"."jobs"
    ADD COLUMN IF NOT EXISTS "is_filtered" boolean DEFAULT false,
    ADD COLUMN IF NOT EXISTS "filter_reason" "text",
    ADD COLUMN IF NOT EXISTS "is_entry_level_filtered" boolean DEFAULT false;

ALTER TABLE "public"."jobs"
    ADD COLUMN IF NOT EXISTS "search_query" text,
    ADD COLUMN IF NOT EXISTS "archetype" text,
    ADD COLUMN IF NOT EXISTS "filter_profile" text;

COMMENT ON COLUMN "public"."jobs"."is_filtered" IS 'True if this job was flagged by the post-scrape filter as irrelevant (wrong domain, non-PM role, etc). Excluded from LLM scoring.';
COMMENT ON COLUMN "public"."jobs"."filter_reason" IS 'Which filter rule triggered the flag, e.g. "title:construction" or "desc:construction firm". Used for auditing and regex refinement.';
COMMENT ON COLUMN "public"."jobs"."is_entry_level_filtered" IS 'True if filtered specifically because of an entry-level/coordinator title (regardless of industry). UI can expose these separately — pivot from IT PM to construction coordinator is feasible, PM to construction senior PM is not.';
COMMENT ON COLUMN "public"."jobs"."archetype" IS 'Normalized search family used for filtering and insights partitioning. Current default: software_tpm.';
COMMENT ON COLUMN "public"."jobs"."search_query" IS 'Exact query string used when the job was scraped.';
COMMENT ON COLUMN "public"."jobs"."filter_profile" IS 'Versioned filter ruleset applied to the job when evaluating is_filtered.';

CREATE INDEX IF NOT EXISTS "idx_jobs_is_filtered" ON "public"."jobs" ("is_filtered");
CREATE INDEX IF NOT EXISTS "idx_jobs_is_entry_level_filtered" ON "public"."jobs" ("is_entry_level_filtered");
CREATE INDEX IF NOT EXISTS "idx_jobs_archetype" ON "public"."jobs" ("archetype");
CREATE INDEX IF NOT EXISTS "idx_jobs_provider_archetype" ON "public"."jobs" ("provider", "archetype");
CREATE INDEX IF NOT EXISTS "idx_jobs_archetype_filtered" ON "public"."jobs" ("archetype", "is_filtered");
CREATE INDEX IF NOT EXISTS "idx_jobs_search_query" ON "public"."jobs" ("search_query");

-- Migration: add canonical role storage and repost tracking columns
ALTER TABLE "public"."jobs"
    ADD COLUMN IF NOT EXISTS "canonical_key" text,
    ADD COLUMN IF NOT EXISTS "original_job_id" text,
    ADD COLUMN IF NOT EXISTS "latest_job_id" text,
    ADD COLUMN IF NOT EXISTS "last_seen_posted_at" timestamp with time zone,
    ADD COLUMN IF NOT EXISTS "posted_relative_text" text,
    ADD COLUMN IF NOT EXISTS "applicant_count" integer,
    ADD COLUMN IF NOT EXISTS "applicant_count_text" text,
    ADD COLUMN IF NOT EXISTS "applicant_count_type" text,
    ADD COLUMN IF NOT EXISTS "salary_text" text,
    ADD COLUMN IF NOT EXISTS "salary_min" numeric,
    ADD COLUMN IF NOT EXISTS "salary_max" numeric,
    ADD COLUMN IF NOT EXISTS "salary_currency" text,
    ADD COLUMN IF NOT EXISTS "recruiter_name" text,
    ADD COLUMN IF NOT EXISTS "recruiter_profile_url" text,
    ADD COLUMN IF NOT EXISTS "recruiter_identifier" text,
    ADD COLUMN IF NOT EXISTS "detail_metadata_checked_at" timestamp with time zone,
    ADD COLUMN IF NOT EXISTS "description_fingerprint" text,
    ADD COLUMN IF NOT EXISTS "first_seen_at" timestamp with time zone DEFAULT now(),
    ADD COLUMN IF NOT EXISTS "last_seen_at" timestamp with time zone DEFAULT now(),
    ADD COLUMN IF NOT EXISTS "seen_count" integer DEFAULT 1,
    ADD COLUMN IF NOT EXISTS "posting_wave_count" integer NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS "repost_count" integer DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "listing_instances" jsonb DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS "same_id_relist_count" integer NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS "idx_jobs_canonical_key" ON "public"."jobs" ("canonical_key");
CREATE INDEX IF NOT EXISTS "idx_jobs_company_title_location" ON "public"."jobs" ("company", "job_title", "location");

COMMENT ON COLUMN "public"."jobs"."applicant_count_text" IS 'Raw LinkedIn applicant caption preserving display semantics.';
COMMENT ON COLUMN "public"."jobs"."applicant_count_type" IS 'Interpretation of applicant_count: exact, upper_bound, or lower_bound.';
COMMENT ON COLUMN "public"."jobs"."detail_metadata_checked_at" IS 'Last LinkedIn detail-page metadata check, including unavailable responses.';
CREATE INDEX IF NOT EXISTS "idx_jobs_last_seen_at" ON "public"."jobs" ("last_seen_at");
CREATE INDEX IF NOT EXISTS "idx_jobs_last_seen_posted_at" ON "public"."jobs" ("last_seen_posted_at");


COMMENT ON COLUMN "public"."jobs"."job_id" IS 'Canonical row identifier for the stored job record. For LinkedIn canonical rows, this is the stable row anchor, not necessarily the latest live LinkedIn posting ID.';
COMMENT ON COLUMN "public"."jobs"."original_job_id" IS 'First LinkedIn listing ID observed for this canonical role.';
COMMENT ON COLUMN "public"."jobs"."latest_job_id" IS 'Most recent LinkedIn listing ID observed for this canonical role. Use this for outbound LinkedIn fetches.';
COMMENT ON COLUMN "public"."jobs"."listing_instances" IS 'Append-only listing history for repost tracking, including per-listing scrape metadata.';
COMMENT ON COLUMN "public"."jobs"."seen_count" IS 'Distinct source listing-ID count retained for compatibility.';
COMMENT ON COLUMN "public"."jobs"."posting_wave_count" IS 'Maximum chronological posting-wave count for one normalized location in listing_instances.';
COMMENT ON COLUMN "public"."jobs"."repost_count" IS 'Confirmed later posting waves: greatest(posting_wave_count - 1, 0). Simultaneous and location variants do not increment it.';
COMMENT ON COLUMN "public"."jobs"."same_id_relist_count" IS 'Conservative lower bound for accepted same-ID relist events: the listing was relisted at least once when greater than zero.';

-- Migration: add the Freehire publication compatibility contract
ALTER TABLE "public"."jobs"
    ADD COLUMN IF NOT EXISTS "freehire_category" text,
    ADD COLUMN IF NOT EXISTS "freehire_seniority" text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "is_remote" boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "freehire_remote_evidence" jsonb,
    ADD COLUMN IF NOT EXISTS "freehire_compat_status" text NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS "freehire_compat_input_hash" text,
    ADD COLUMN IF NOT EXISTS "freehire_compat_import_hash" text,
    ADD COLUMN IF NOT EXISTS "freehire_compat_model" text,
    ADD COLUMN IF NOT EXISTS "freehire_compat_prompt_version" text,
    ADD COLUMN IF NOT EXISTS "freehire_compat_schema_version" text,
    ADD COLUMN IF NOT EXISTS "freehire_compat_confidence" numeric,
    ADD COLUMN IF NOT EXISTS "freehire_compat_classified_at" timestamptz,
    ADD COLUMN IF NOT EXISTS "freehire_compat_error" text,
    ADD COLUMN IF NOT EXISTS "freehire_compat_attempts" integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "freehire_compat_claimed_at" timestamptz,
    ADD COLUMN IF NOT EXISTS "freehire_compat_claimed_by" text,
    ADD COLUMN IF NOT EXISTS "freehire_compat_provenance" jsonb,
    ADD COLUMN IF NOT EXISTS "freehire_compat_next_retry_at" timestamptz;

UPDATE "public"."jobs"
SET "freehire_compat_status" = 'pending'
WHERE "provider" = 'linkedin'
  AND "freehire_compat_status" = 'current'
  AND (
      "freehire_compat_input_hash" IS NULL
      OR "freehire_compat_schema_version" IS DISTINCT FROM 'freehire-compat-v1'
      OR "freehire_compat_prompt_version" IS DISTINCT FROM 'freehire-category-v1'
      OR "freehire_category" IS NULL
  );

ALTER TABLE "public"."jobs" DROP CONSTRAINT IF EXISTS "jobs_freehire_category_check";
ALTER TABLE "public"."jobs" ADD CONSTRAINT "jobs_freehire_category_check" CHECK (
    "freehire_category" IS NULL OR "freehire_category" IN (
        'software_engineering', 'backend', 'frontend', 'fullstack', 'mobile',
        'devops', 'sre', 'network_engineering', 'data_engineering', 'data_science',
        'data_analytics', 'ml_ai', 'ai_engineering', 'qa', 'security', 'hardware',
        'embedded', 'blockchain', 'architecture', 'design', 'engineering_design',
        'product', 'project_management', 'management', 'marketing', 'sales',
        'support', 'business_analysis', 'solutions_engineering', 'developer_relations',
        'technical_writing', 'recruiting', 'hr', 'finance', 'legal', 'operations',
        'customer_success', 'other'
    )
);
ALTER TABLE "public"."jobs" DROP CONSTRAINT IF EXISTS "jobs_freehire_seniority_check";
ALTER TABLE "public"."jobs" ADD CONSTRAINT "jobs_freehire_seniority_check" CHECK (
    "freehire_seniority" IN ('', 'intern', 'junior', 'middle', 'senior', 'lead', 'staff', 'principal', 'c_level')
);
ALTER TABLE "public"."jobs" DROP CONSTRAINT IF EXISTS "jobs_freehire_compat_status_check";
ALTER TABLE "public"."jobs" ADD CONSTRAINT "jobs_freehire_compat_status_check" CHECK (
    "freehire_compat_status" IN ('pending', 'processing', 'current', 'failed')
);
ALTER TABLE "public"."jobs" DROP CONSTRAINT IF EXISTS "jobs_freehire_compat_confidence_check";
ALTER TABLE "public"."jobs" ADD CONSTRAINT "jobs_freehire_compat_confidence_check" CHECK (
    "freehire_compat_confidence" IS NULL OR "freehire_compat_confidence" BETWEEN 0 AND 1
);

CREATE INDEX IF NOT EXISTS "idx_jobs_freehire_compat_status" ON "public"."jobs" ("provider", "freehire_compat_status");
CREATE INDEX IF NOT EXISTS "idx_jobs_freehire_compat_input_hash" ON "public"."jobs" ("freehire_compat_input_hash");
CREATE INDEX IF NOT EXISTS "idx_jobs_freehire_compat_retry" ON "public"."jobs" ("freehire_compat_status", "freehire_compat_next_retry_at") WHERE "provider" = 'linkedin';

COMMENT ON COLUMN "public"."jobs"."freehire_category" IS 'Pinned Freehire category assigned by the compatibility classifier.';
COMMENT ON COLUMN "public"."jobs"."freehire_seniority" IS 'Pinned Freehire seniority; empty means unresolved rather than guessed.';
COMMENT ON COLUMN "public"."jobs"."is_remote" IS 'True only when standalone ASCII remote occurs in normalized visible title, location, or description text.';
COMMENT ON COLUMN "public"."jobs"."freehire_remote_evidence" IS 'Deterministic visible-text match field and normalized span for is_remote=true; null otherwise.';
COMMENT ON COLUMN "public"."jobs"."freehire_compat_status" IS 'Compatibility lifecycle: pending, processing, current, or failed.';
COMMENT ON COLUMN "public"."jobs"."freehire_compat_input_hash" IS 'SHA-256 of canonical classification inputs and schema version; independent of scraped_at.';
COMMENT ON COLUMN "public"."jobs"."freehire_compat_import_hash" IS 'SHA-256 of downstream classification, live ID, effective timestamps, and remote fields.';
COMMENT ON COLUMN "public"."jobs"."freehire_compat_model" IS 'Exact LLM model used for the latest classification attempt.';
COMMENT ON COLUMN "public"."jobs"."freehire_compat_prompt_version" IS 'Version of the strict Freehire classification prompt.';
COMMENT ON COLUMN "public"."jobs"."freehire_compat_schema_version" IS 'Version binding hash normalization and pinned vocabularies.';
COMMENT ON COLUMN "public"."jobs"."freehire_compat_confidence" IS 'Classifier confidence from zero through one.';
COMMENT ON COLUMN "public"."jobs"."freehire_compat_classified_at" IS 'Timestamp of the latest successful compatibility classification.';
COMMENT ON COLUMN "public"."jobs"."freehire_compat_error" IS 'Last retry-exhausted per-job classification error; null after success.';
COMMENT ON COLUMN "public"."jobs"."freehire_compat_attempts" IS 'Durable count of classification passes attempted for this canonical job.';
COMMENT ON COLUMN "public"."jobs"."freehire_compat_claimed_at" IS 'Worker lease timestamp while status is processing.';
COMMENT ON COLUMN "public"."jobs"."freehire_compat_claimed_by" IS 'Worker identifier owning the current processing lease.';
COMMENT ON COLUMN "public"."jobs"."freehire_compat_provenance" IS 'Auditable batch, model, prompt, schema, timestamp, or failure provenance.';

CREATE OR REPLACE VIEW "public"."freehire_jobs" AS
SELECT
    "job_id",
    COALESCE("latest_job_id", "job_id") AS "live_listing_id",
    "company", "job_title", "level", "location", "description",
    "posted_at", "scraped_at", "first_seen_at", "last_seen_at", "last_seen_posted_at",
    "last_checked", "detail_metadata_checked_at",
    "freehire_category", "freehire_seniority", "is_remote", "freehire_remote_evidence",
    "freehire_compat_status", "freehire_compat_input_hash", "freehire_compat_import_hash",
    "freehire_compat_model", "freehire_compat_prompt_version", "freehire_compat_schema_version",
    "freehire_compat_confidence", "freehire_compat_classified_at", "freehire_compat_provenance",
    "salary_text", "salary_min", "salary_max", "salary_currency",
    "applicant_count", "applicant_count_text", "applicant_count_type",
    "recruiter_name", "recruiter_profile_url", "recruiter_identifier",
    "original_job_id", "latest_job_id", "seen_count", "posting_wave_count", "repost_count",
    "same_id_relist_count", "listing_instances", "archetype", "search_query", "filter_profile",
    "is_filtered", "is_entry_level_filtered", "filter_reason", "description_fingerprint"
FROM "public"."jobs"
WHERE "provider" = 'linkedin'
  AND "freehire_compat_status" = 'current'
  AND "freehire_category" IS NOT NULL
  AND "freehire_compat_input_hash" IS NOT NULL
  AND "freehire_compat_import_hash" IS NOT NULL
  AND "freehire_compat_model" IS NOT NULL
  AND "freehire_compat_prompt_version" = 'freehire-category-v1'
  AND "freehire_compat_schema_version" = 'freehire-compat-v1';

REVOKE ALL ON "public"."freehire_jobs" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON "public"."freehire_jobs" TO service_role;

CREATE OR REPLACE FUNCTION "public"."invalidate_freehire_compat_input"() RETURNS trigger
    LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
BEGIN
    IF pg_trigger_depth() = 1 AND NEW.provider = 'linkedin' AND (
        OLD.job_id IS DISTINCT FROM NEW.job_id OR OLD.job_title IS DISTINCT FROM NEW.job_title
        OR OLD.location IS DISTINCT FROM NEW.location OR OLD.description IS DISTINCT FROM NEW.description
        OR OLD.level IS DISTINCT FROM NEW.level
    ) THEN
        NEW.freehire_compat_status := 'pending';
        NEW.freehire_compat_input_hash := NULL;
        NEW.freehire_compat_import_hash := NULL;
        NEW.freehire_compat_error := NULL;
        NEW.freehire_compat_claimed_at := NULL;
        NEW.freehire_compat_claimed_by := NULL;
        NEW.freehire_compat_next_retry_at := NULL;
    ELSIF pg_trigger_depth() = 1 AND NEW.provider = 'linkedin'
      AND OLD.freehire_compat_import_hash IS NOT DISTINCT FROM NEW.freehire_compat_import_hash
      AND OLD IS DISTINCT FROM NEW THEN
        NEW.freehire_compat_import_hash := NULL;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "jobs_invalidate_freehire_compat_input" ON "public"."jobs";
CREATE TRIGGER "jobs_invalidate_freehire_compat_input" BEFORE UPDATE ON "public"."jobs"
    FOR EACH ROW EXECUTE FUNCTION "public"."invalidate_freehire_compat_input"();



COMMENT ON COLUMN "public"."jobs"."company" IS 'Company name';



COMMENT ON COLUMN "public"."jobs"."job_title" IS 'Job title';



COMMENT ON COLUMN "public"."jobs"."level" IS 'Seniority level (e.g., ''Entry level'', ''Mid-Senior level'')';



COMMENT ON COLUMN "public"."jobs"."location" IS 'Job location';



COMMENT ON COLUMN "public"."jobs"."description" IS 'Full job description';



COMMENT ON COLUMN "public"."jobs"."status" IS 'Workflow status (e.g., new, scored, applied, interviewing, rejected, expired, archived)';



COMMENT ON COLUMN "public"."jobs"."is_active" IS 'Is the job posting considered active on LinkedIn? (Checked periodically)';



COMMENT ON COLUMN "public"."jobs"."application_date" IS 'Timestamp when an application was submitted/attempted';



COMMENT ON COLUMN "public"."jobs"."resume_score" IS 'Score (0-100) indicating resume match, NULL if not scored yet';



COMMENT ON COLUMN "public"."jobs"."notes" IS 'User''s notes about the job/application';



COMMENT ON COLUMN "public"."jobs"."scraped_at" IS 'Timestamp when the record was first added';



COMMENT ON COLUMN "public"."jobs"."last_checked" IS 'Timestamp when the record was last checked/updated by any script';



CREATE OR REPLACE FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer) RETURNS SETOF "public"."jobs"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN QUERY
  SELECT *
  FROM jobs
  WHERE 
    is_active = TRUE AND
    job_state = 'new' AND
    status IN ('applied', 'interviewing', 'offered') -- Ensure these are the exact status strings in your DB
  ORDER BY
    CASE status
      WHEN 'offered' THEN 1
      WHEN 'interviewing' THEN 2
      WHEN 'applied' THEN 3
      ELSE 4 -- Should ideally not be reached due to the IN clause
    END ASC,
    application_date DESC
  LIMIT p_page_size
  OFFSET (p_page_number - 1) * p_page_size;
END;
$$;


ALTER FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text" DEFAULT NULL::"text", "p_search_query" "text" DEFAULT NULL::"text") RETURNS SETOF "public"."jobs"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN QUERY
  SELECT *
  FROM jobs j -- Added alias 'j' for clarity
  WHERE
    j.is_active = TRUE AND
    j.job_state = 'new' AND
    j.status IN ('applied', 'interviewing', 'offer') -- Corrected 'offered' to 'offer' as per your count function
    -- Conditionally apply provider filter
    AND (p_provider IS NULL OR j.provider = p_provider)
    -- Conditionally apply search query filter
    AND (
      p_search_query IS NULL OR
      j.job_title ILIKE '%' || p_search_query || '%' OR
      j.company ILIKE '%' || p_search_query || '%'
      -- Add other fields to search if needed, e.g.:
      -- OR j.job_description ILIKE '%' || p_search_query || '%'
    )
  ORDER BY
    CASE j.status
      WHEN 'offer' THEN 1       -- Corrected 'offered' to 'offer'
      WHEN 'interviewing' THEN 2
      WHEN 'applied' THEN 3
      ELSE 4
    END ASC,
    j.application_date DESC
  LIMIT p_page_size
  OFFSET (p_page_number - 1) * p_page_size;
END;
$$;


ALTER FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_search_query" "text") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text" DEFAULT NULL::"text", "p_search_query" "text" DEFAULT NULL::"text", "p_application_status" "text" DEFAULT NULL::"text") RETURNS SETOF "public"."jobs"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN QUERY
  SELECT *
  FROM jobs j
  WHERE
    j.is_active = TRUE AND
    j.job_state = 'new' AND
    -- Conditionally apply application status filter
    (
      p_application_status IS NULL AND j.status IN ('applied', 'interviewing', 'offer') OR
      j.status = p_application_status
    )
    -- Conditionally apply provider filter
    AND (p_provider IS NULL OR j.provider = p_provider)
    -- Conditionally apply search query filter
    AND (
      p_search_query IS NULL OR
      j.job_title ILIKE '%' || p_search_query || '%' OR
      j.company ILIKE '%' || p_search_query || '%'
    )
  ORDER BY
    CASE j.status
      WHEN 'offer' THEN 1
      WHEN 'interviewing' THEN 2
      WHEN 'applied' THEN 3
      ELSE 4
    END ASC,
    j.application_date DESC
  LIMIT p_page_size
  OFFSET (p_page_number - 1) * p_page_size;
END;
$$;


ALTER FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_search_query" "text", "p_application_status" "text") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text" DEFAULT NULL::"text", "p_search_query" "text" DEFAULT NULL::"text", "p_application_status" "text" DEFAULT NULL::"text", "p_sort_by" "text" DEFAULT NULL::"text", "p_sort_order" "text" DEFAULT 'desc'::"text") RETURNS SETOF "public"."jobs"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN QUERY
  SELECT *
  FROM jobs j
  WHERE
    j.is_active = TRUE AND
    j.job_state = 'new' AND
    -- Conditionally apply application status filter
    (
      p_application_status IS NULL AND j.status IN ('applied', 'interviewing', 'offer') OR
      j.status = p_application_status
    )
    -- Conditionally apply provider filter
    AND (p_provider IS NULL OR j.provider = p_provider)
    -- Conditionally apply search query filter
    AND (
      p_search_query IS NULL OR
      j.job_title ILIKE '%' || p_search_query || '%' OR
      j.company ILIKE '%' || p_search_query || '%'
    )
  ORDER BY
    -- Primary sort based on p_sort_by and p_sort_order
    CASE
      WHEN p_sort_by = 'application_date' AND p_sort_order = 'asc' THEN j.application_date
      ELSE NULL -- Allows other CASE WHENs or the default sort to take over
    END ASC NULLS LAST,
    CASE
      WHEN p_sort_by = 'application_date' AND p_sort_order = 'desc' THEN j.application_date
      ELSE NULL
    END DESC NULLS LAST,
    CASE
      WHEN p_sort_by = 'resume_score' AND p_sort_order = 'asc' THEN j.resume_score
      ELSE NULL
    END ASC NULLS LAST,
    CASE
      WHEN p_sort_by = 'resume_score' AND p_sort_order = 'desc' THEN j.resume_score
      ELSE NULL
    END DESC NULLS LAST,
    -- Secondary / Default sort: by status priority, then by application_date descending
    CASE j.status
      WHEN 'offer' THEN 1
      WHEN 'interviewing' THEN 2
      WHEN 'applied' THEN 3
      ELSE 4
    END ASC,
    j.application_date DESC
  LIMIT p_page_size
  OFFSET (p_page_number - 1) * p_page_size;
END;
$$;


ALTER FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_search_query" "text", "p_application_status" "text", "p_sort_by" "text", "p_sort_order" "text") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_jobs_for_rescore"("p_limit_val" integer) RETURNS TABLE("job_id" "text", "job_title" "text", "company" "text", "description" "text", "level" "text", "resume_score" smallint, "resume_link" "text", "customized_resume_id" "uuid")
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    RETURN QUERY
    SELECT
        j.job_id,
        j.job_title,
        j.company,
        j.description,
        j.level,
        j.resume_score,
        cr.resume_link,
        j.customized_resume_id
    FROM
        jobs j
    INNER JOIN
        customized_resumes cr ON j.customized_resume_id = cr.id
    WHERE
        j.is_active = TRUE
        AND j.status = 'new'
        AND j.job_state = 'new'
        AND j.is_filtered = FALSE
        AND j.customized_resume_id IS NOT NULL
        AND cr.resume_link IS NOT NULL
        AND j.resume_score_stage = 'initial'
        AND j.is_interested IS NOT FALSE
    ORDER BY
        j.resume_score DESC
    LIMIT
        p_limit_val;
END;
$$;


ALTER FUNCTION "public"."get_jobs_for_rescore"("p_limit_val" integer) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_jobs_for_resume_generation_custom_sort"("p_page_number" integer, "p_page_size" integer) RETURNS TABLE("job_id" "text", "company" "text", "job_title" "text", "level" "text", "location" "text", "description" "text", "status" "text", "is_active" boolean, "application_date" timestamp with time zone, "resume_score" smallint, "notes" "text", "scraped_at" timestamp with time zone, "last_checked" timestamp with time zone, "job_state" "text", "resume_score_stage" "text", "is_interested" boolean, "customized_resume_id" "uuid", "provider" "text")
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    RETURN QUERY
    SELECT
        j.job_id,
        j.company,
        j.job_title,
        j.level,
        j.location,
        j.description,
        j.status,
        j.is_active,
        j.application_date,
        j.resume_score,
        j.notes,
        j.scraped_at,
        j.last_checked,
        j.job_state,
        j.resume_score_stage,
        j.is_interested,
        j.customized_resume_id, -- Still selected, will be NULL
        j.provider
    FROM
        jobs j
    WHERE
        j.is_active = TRUE
        AND j.status = 'new'
        AND j.job_state = 'new'
        AND j.is_filtered = FALSE
        AND j.resume_score >= 50
        AND j.customized_resume_id IS NULL -- Key new filter
    ORDER BY
        CASE
            WHEN j.is_interested IS TRUE THEN 1
            WHEN j.is_interested IS NULL THEN 2
            ELSE 3
        END ASC,
        j.resume_score DESC
    LIMIT p_page_size
    OFFSET (p_page_number - 1) * p_page_size;
END;
$$;


ALTER FUNCTION "public"."get_jobs_for_resume_generation_custom_sort"("p_page_number" integer, "p_page_size" integer) OWNER TO "postgres";


DROP FUNCTION IF EXISTS "public"."get_top_scored_jobs_custom_sort"(integer, integer, text, integer, integer, text);


CREATE OR REPLACE FUNCTION "public"."get_top_scored_jobs_custom_sort"("p_page_number" integer, "p_page_size" integer, "p_provider" "text" DEFAULT NULL::"text", "p_min_score" integer DEFAULT 50, "p_max_score" integer DEFAULT 100, "p_is_interested_option" "text" DEFAULT NULL::"text", "p_search_query" "text" DEFAULT NULL::"text") RETURNS TABLE("job_id" "text", "company" "text", "job_title" "text", "level" "text", "location" "text", "description" "text", "status" "text", "is_active" boolean, "application_date" timestamp with time zone, "resume_score" smallint, "notes" "text", "scraped_at" timestamp with time zone, "last_checked" timestamp with time zone, "job_state" "text", "resume_score_stage" "text", "is_interested" boolean, "customized_resume_id" "uuid", "resume_link" "text", "provider" "text")
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    RETURN QUERY
    SELECT
        j.job_id,
        j.company,
        j.job_title,
        j.level,
        j.location,
        j.description,
        j.status,
        j.is_active,
        j.application_date,
        j.resume_score,
        j.notes,
        j.scraped_at,
        j.last_checked,
        j.job_state,
        j.resume_score_stage,
        j.is_interested,
        j.customized_resume_id,
        cr.resume_link,
        j.provider
    FROM
        jobs j
    INNER JOIN
        customized_resumes cr ON j.customized_resume_id = cr.id
    WHERE
        j.is_active = TRUE
        AND j.status = 'new'
        AND j.job_state = 'new'
        AND j.is_filtered = FALSE
        AND j.resume_score >= p_min_score
        AND j.resume_score <= p_max_score
        AND (p_provider IS NULL OR j.provider = p_provider)
        AND (
            p_is_interested_option IS NULL
            OR (p_is_interested_option = 'true' AND j.is_interested IS TRUE)
            OR (p_is_interested_option = 'false' AND j.is_interested IS FALSE)
            OR (p_is_interested_option = 'null_value' AND j.is_interested IS NULL)
        )
        AND ( -- Added search query condition
            p_search_query IS NULL 
            OR j.job_title ILIKE '%' || p_search_query || '%'
            OR j.company ILIKE '%' || p_search_query || '%'
        )
    ORDER BY
        CASE
            WHEN j.is_interested IS TRUE THEN 1
            WHEN j.is_interested IS NULL THEN 2
            WHEN j.is_interested IS FALSE THEN 3
            ELSE 4
        END,
        CASE
            WHEN j.resume_score_stage = 'custom' THEN 1
            WHEN j.resume_score_stage = 'initial' THEN 2
            ELSE 3
        END,
        j.resume_score DESC NULLS LAST,
        j.scraped_at DESC
    LIMIT p_page_size
    OFFSET (p_page_number - 1) * p_page_size;
END;
$$;


ALTER FUNCTION "public"."get_top_scored_jobs_custom_sort"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_min_score" integer, "p_max_score" integer, "p_is_interested_option" "text", "p_search_query" "text") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_last_updated_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
   NEW.last_updated = now();
   RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_last_updated_column"() OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."customized_resumes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "email" "text" NOT NULL,
    "phone" "text",
    "location" "text",
    "summary" "text",
    "skills" "text"[],
    "education" "jsonb",
    "experience" "jsonb",
    "projects" "jsonb",
    "certifications" "jsonb",
    "languages" "text"[],
    "links" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "last_updated" timestamp with time zone DEFAULT "now"(),
    "resume_link" "text"
);


ALTER TABLE "public"."customized_resumes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."keyword_insights" (
    "archetype" text NOT NULL,
    "keyword" text NOT NULL,
    "category" text NOT NULL,
    "count" integer DEFAULT 0 NOT NULL,
    "provider" text DEFAULT 'unknown'::text NOT NULL,
    "last_updated" timestamp with time zone DEFAULT now(),
    CONSTRAINT "keyword_insights_category_check"
        CHECK ("category" IN ('skill', 'technology', 'certification', 'attribute')),
    CONSTRAINT "keyword_insights_count_check"
        CHECK ("count" >= 0)
);


ALTER TABLE "public"."keyword_insights" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."job_keyword_insights" (
    "job_id" text NOT NULL,
    "archetype" text NOT NULL,
    "keyword" text NOT NULL,
    "category" text NOT NULL,
    "provider" text,
    "analyzed_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "job_keyword_insights_category_check"
        CHECK ("category" IN ('skill', 'technology', 'certification', 'attribute'))
);


ALTER TABLE "public"."job_keyword_insights" OWNER TO "postgres";
















DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.customized_resumes'::regclass AND contype = 'p') THEN
        ALTER TABLE ONLY "public"."customized_resumes" ADD CONSTRAINT "customized_resumes_pkey" PRIMARY KEY ("id");
    END IF;
END $$;


DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.keyword_insights'::regclass AND contype = 'p') THEN
        ALTER TABLE ONLY "public"."keyword_insights" ADD CONSTRAINT "keyword_insights_pkey" PRIMARY KEY ("archetype", "provider", "keyword", "category");
    END IF;
END $$;


DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.job_keyword_insights'::regclass AND contype = 'p') THEN
        ALTER TABLE ONLY "public"."job_keyword_insights" ADD CONSTRAINT "job_keyword_insights_pkey" PRIMARY KEY ("job_id", "archetype", "keyword", "category");
    END IF;
END $$;



DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.jobs'::regclass AND contype = 'p') THEN
        ALTER TABLE ONLY "public"."jobs" ADD CONSTRAINT "jobs_pkey" PRIMARY KEY ("job_id");
    END IF;
END $$;

DO $$ BEGIN ALTER TABLE ONLY "public"."listing_observations" ADD CONSTRAINT "listing_observations_canonical_job_id_fkey" FOREIGN KEY ("canonical_job_id") REFERENCES "public"."jobs"("job_id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE ONLY "public"."listing_content_versions" ADD CONSTRAINT "listing_content_versions_canonical_job_id_fkey" FOREIGN KEY ("canonical_job_id") REFERENCES "public"."jobs"("job_id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE ONLY "public"."listing_relist_events" ADD CONSTRAINT "listing_relist_events_canonical_job_id_fkey" FOREIGN KEY ("canonical_job_id") REFERENCES "public"."jobs"("job_id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE ONLY "public"."listing_states" ADD CONSTRAINT "listing_states_canonical_job_id_fkey" FOREIGN KEY ("canonical_job_id") REFERENCES "public"."jobs"("job_id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE ONLY "public"."listing_observations" ADD CONSTRAINT "listing_observations_ingestion_run_id_fkey" FOREIGN KEY ("ingestion_run_id") REFERENCES "public"."ingestion_runs"("id") ON DELETE RESTRICT; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE ONLY "public"."listing_content_versions" ADD CONSTRAINT "listing_content_versions_last_ingestion_run_id_fkey" FOREIGN KEY ("last_ingestion_run_id") REFERENCES "public"."ingestion_runs"("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE ONLY "public"."listing_relist_events" ADD CONSTRAINT "listing_relist_events_ingestion_run_id_fkey" FOREIGN KEY ("ingestion_run_id") REFERENCES "public"."ingestion_runs"("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE ONLY "public"."listing_relist_events" ADD CONSTRAINT "listing_relist_events_superseded_by_fkey" FOREIGN KEY ("superseded_by") REFERENCES "public"."listing_relist_events"("id") ON DELETE RESTRICT; EXCEPTION WHEN duplicate_object THEN NULL; END $$;











CREATE INDEX IF NOT EXISTS "idx_jobs_company" ON "public"."jobs" USING "btree" ("company");



CREATE INDEX IF NOT EXISTS "idx_jobs_is_active" ON "public"."jobs" USING "btree" ("is_active");



CREATE INDEX IF NOT EXISTS "idx_jobs_job_title" ON "public"."jobs" USING "btree" ("job_title");



CREATE INDEX IF NOT EXISTS "idx_jobs_last_checked" ON "public"."jobs" USING "btree" ("last_checked");


CREATE INDEX IF NOT EXISTS "idx_jobs_insights_analyzed_at" ON "public"."jobs" USING "btree" ("insights_analyzed_at");


CREATE INDEX IF NOT EXISTS "idx_jobs_insights_reanalyzed_at" ON "public"."jobs" USING "btree" ("insights_reanalyzed_at");



CREATE INDEX IF NOT EXISTS "idx_jobs_resume_score" ON "public"."jobs" USING "btree" ("resume_score");



CREATE INDEX IF NOT EXISTS "idx_jobs_scraped_at" ON "public"."jobs" USING "btree" ("scraped_at");



CREATE INDEX IF NOT EXISTS "idx_jobs_status" ON "public"."jobs" USING "btree" ("status");


CREATE INDEX IF NOT EXISTS "idx_keyword_insights_category" ON "public"."keyword_insights" USING "btree" ("category");


CREATE INDEX IF NOT EXISTS "idx_keyword_insights_archetype_category" ON "public"."keyword_insights" USING "btree" ("archetype", "category");


CREATE INDEX IF NOT EXISTS "idx_keyword_insights_count" ON "public"."keyword_insights" USING "btree" ("count" DESC);


CREATE INDEX IF NOT EXISTS "idx_job_keyword_insights_job_id" ON "public"."job_keyword_insights" USING "btree" ("job_id");


CREATE INDEX IF NOT EXISTS "idx_job_keyword_insights_archetype" ON "public"."job_keyword_insights" USING "btree" ("archetype");


CREATE INDEX IF NOT EXISTS "idx_job_keyword_insights_keyword_category" ON "public"."job_keyword_insights" USING "btree" ("keyword", "category");



CREATE OR REPLACE TRIGGER "update_customized_resumes_last_updated" BEFORE UPDATE ON "public"."customized_resumes" FOR EACH ROW EXECUTE FUNCTION "public"."update_last_updated_column"();


CREATE OR REPLACE TRIGGER "update_keyword_insights_last_updated" BEFORE UPDATE ON "public"."keyword_insights" FOR EACH ROW EXECUTE FUNCTION "public"."update_last_updated_column"();



DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.jobs'::regclass
          AND conname = 'jobs_customized_resume_id_fkey'
    ) THEN
        ALTER TABLE ONLY "public"."jobs"
            ADD CONSTRAINT "jobs_customized_resume_id_fkey" FOREIGN KEY ("customized_resume_id") REFERENCES "public"."customized_resumes"("id") ON UPDATE CASCADE ON DELETE SET NULL;
    END IF;
END $$;



ALTER TABLE "public"."customized_resumes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."keyword_insights" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."job_keyword_insights" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."jobs" ENABLE ROW LEVEL SECURITY;







ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


GRANT ALL ON TABLE "public"."jobs" TO "anon";
GRANT ALL ON TABLE "public"."jobs" TO "authenticated";
GRANT ALL ON TABLE "public"."jobs" TO "service_role";



GRANT ALL ON FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_search_query" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_search_query" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_search_query" "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_search_query" "text", "p_application_status" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_search_query" "text", "p_application_status" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_search_query" "text", "p_application_status" "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_search_query" "text", "p_application_status" "text", "p_sort_by" "text", "p_sort_order" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_search_query" "text", "p_application_status" "text", "p_sort_by" "text", "p_sort_order" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_applied_jobs_sorted"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_search_query" "text", "p_application_status" "text", "p_sort_by" "text", "p_sort_order" "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."get_jobs_for_rescore"("p_limit_val" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."get_jobs_for_rescore"("p_limit_val" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_jobs_for_rescore"("p_limit_val" integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."get_jobs_for_resume_generation_custom_sort"("p_page_number" integer, "p_page_size" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."get_jobs_for_resume_generation_custom_sort"("p_page_number" integer, "p_page_size" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_jobs_for_resume_generation_custom_sort"("p_page_number" integer, "p_page_size" integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."get_top_scored_jobs_custom_sort"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_min_score" integer, "p_max_score" integer, "p_is_interested_option" "text", "p_search_query" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."get_top_scored_jobs_custom_sort"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_min_score" integer, "p_max_score" integer, "p_is_interested_option" "text", "p_search_query" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_top_scored_jobs_custom_sort"("p_page_number" integer, "p_page_size" integer, "p_provider" "text", "p_min_score" integer, "p_max_score" integer, "p_is_interested_option" "text", "p_search_query" "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."update_last_updated_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_last_updated_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_last_updated_column"() TO "service_role";


GRANT ALL ON TABLE "public"."customized_resumes" TO "anon";
GRANT ALL ON TABLE "public"."customized_resumes" TO "authenticated";
GRANT ALL ON TABLE "public"."customized_resumes" TO "service_role";


GRANT ALL ON TABLE "public"."keyword_insights" TO "anon";
GRANT ALL ON TABLE "public"."keyword_insights" TO "authenticated";
GRANT ALL ON TABLE "public"."keyword_insights" TO "service_role";


GRANT ALL ON TABLE "public"."job_keyword_insights" TO "anon";
GRANT ALL ON TABLE "public"."job_keyword_insights" TO "authenticated";
GRANT ALL ON TABLE "public"."job_keyword_insights" TO "service_role";











ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";







-- --- Required standalone migration functions ---
CREATE OR REPLACE FUNCTION public.apply_linkedin_relist_projection(
    p_canonical_job_id text,
    p_source_job_id text,
    p_ingestion_run_id uuid,
    p_relisted_on date,
    p_observed_at timestamptz,
    p_projection jsonb,
    p_expected_listing_instances jsonb,
    p_expected_last_seen_at timestamptz,
    p_evidence jsonb,
    p_description text,
    p_content_hash text,
    p_description_fingerprint text
) RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    affected integer;
BEGIN
    IF p_relisted_on IS NULL OR p_content_hash IS NULL OR p_description IS NULL THEN
        RETURN false;
    END IF;
    UPDATE public.jobs
    SET listing_instances = p_projection->'listing_instances',
        seen_count = (p_projection->>'seen_count')::integer,
        posting_wave_count = (p_projection->>'posting_wave_count')::integer,
        repost_count = (p_projection->>'repost_count')::integer,
        same_id_relist_count = (p_projection->>'same_id_relist_count')::integer,
        latest_job_id = p_projection->>'latest_job_id',
        last_seen_at = (p_projection->>'last_seen_at')::timestamptz,
        last_seen_posted_at = NULLIF(p_projection->>'last_seen_posted_at', '')::timestamptz,
        description = COALESCE(p_projection->>'description', description),
        description_fingerprint = COALESCE(p_projection->>'description_fingerprint', description_fingerprint),
        is_active = COALESCE((p_projection->>'is_active')::boolean, is_active),
        job_state = COALESCE(p_projection->>'job_state', job_state)
    WHERE job_id = p_canonical_job_id
      AND listing_instances = p_expected_listing_instances
      AND last_seen_at IS NOT DISTINCT FROM p_expected_last_seen_at;
    GET DIAGNOSTICS affected = ROW_COUNT;
    IF affected <> 1 THEN
        RETURN false;
    END IF;

    INSERT INTO public.listing_relist_events (
        provider, source_job_id, canonical_job_id, relisted_on, observed_at,
        ingestion_run_id, evidence
    ) VALUES (
        'linkedin', p_source_job_id, p_canonical_job_id, p_relisted_on,
        p_observed_at, p_ingestion_run_id, COALESCE(p_evidence, '{}'::jsonb)
    ) ON CONFLICT (provider, source_job_id, relisted_on) DO NOTHING;

    INSERT INTO public.listing_content_versions (
        provider, source_job_id, content_hash, canonical_job_id, description,
        description_fingerprint, first_observed_at, last_observed_at,
        observation_count, last_ingestion_run_id
    ) VALUES (
        'linkedin', p_source_job_id, p_content_hash, p_canonical_job_id,
        p_description, p_description_fingerprint, p_observed_at, p_observed_at,
        1, p_ingestion_run_id
    ) ON CONFLICT (provider, source_job_id, content_hash) DO UPDATE SET
        canonical_job_id = EXCLUDED.canonical_job_id,
        description = EXCLUDED.description,
        description_fingerprint = EXCLUDED.description_fingerprint,
        last_observed_at = GREATEST(listing_content_versions.last_observed_at, EXCLUDED.last_observed_at),
        last_ingestion_run_id = EXCLUDED.last_ingestion_run_id,
        observation_count = CASE
            WHEN listing_content_versions.last_ingestion_run_id IS DISTINCT FROM EXCLUDED.last_ingestion_run_id
            THEN listing_content_versions.observation_count + 1
            ELSE listing_content_versions.observation_count
        END;

    INSERT INTO public.listing_states (
        provider, source_job_id, canonical_job_id, first_seen_at, last_seen_at,
        latest_trusted_posted_date, current_content_hash, same_id_relist_count
    ) VALUES (
        'linkedin', p_source_job_id, p_canonical_job_id, p_observed_at,
        p_observed_at, p_relisted_on, p_content_hash,
        (p_projection->>'same_id_relist_count')::integer
    ) ON CONFLICT (provider, source_job_id) DO UPDATE SET
        canonical_job_id = EXCLUDED.canonical_job_id,
        last_seen_at = EXCLUDED.last_seen_at,
        latest_trusted_posted_date = EXCLUDED.latest_trusted_posted_date,
        current_content_hash = EXCLUDED.current_content_hash,
        same_id_relist_count = GREATEST(listing_states.same_id_relist_count, EXCLUDED.same_id_relist_count),
        updated_at = now();

    UPDATE public.listing_states
    SET pending_relist_on = NULL,
        same_id_relist_count = GREATEST(
            same_id_relist_count,
            (p_projection->>'same_id_relist_count')::integer
        ),
        current_content_hash = p_content_hash,
        updated_at = now()
    WHERE provider = 'linkedin'
      AND source_job_id = p_source_job_id
      AND pending_relist_on = p_relisted_on;

    RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.apply_freehire_compat_metadata(
    p_job_id text,
    p_expected_source_snapshot jsonb,
    p_payload jsonb
) RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    affected integer;
BEGIN
    UPDATE public.jobs AS j
    SET is_remote = (p_payload->>'is_remote')::boolean,
        freehire_remote_evidence = p_payload->'freehire_remote_evidence',
        freehire_compat_import_hash = p_payload->>'freehire_compat_import_hash'
    WHERE job_id = p_job_id
      AND provider = 'linkedin'
      AND freehire_compat_status = 'current'
      AND p_expected_source_snapshot <@ to_jsonb(j);
    GET DIAGNOSTICS affected = ROW_COUNT;
    RETURN affected = 1;
END;
$$;

CREATE OR REPLACE FUNCTION public.apply_same_id_relist_repair(
    p_canonical_job_id text,
    p_expected_listing_instances jsonb,
    p_expected_last_seen_at timestamptz,
    p_payload jsonb
) RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    affected integer;
BEGIN
    UPDATE public.jobs
    SET listing_instances = p_payload->'listing_instances',
        seen_count = (p_payload->>'seen_count')::integer,
        posting_wave_count = (p_payload->>'posting_wave_count')::integer,
        repost_count = (p_payload->>'repost_count')::integer,
        same_id_relist_count = (p_payload->>'same_id_relist_count')::integer
    WHERE job_id = p_canonical_job_id
      AND listing_instances IS NOT DISTINCT FROM p_expected_listing_instances
      AND last_seen_at IS NOT DISTINCT FROM p_expected_last_seen_at;
    GET DIAGNOSTICS affected = ROW_COUNT;
    RETURN affected = 1;
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_freehire_compat_job(
    p_job_id text,
    p_expected_input_hash text,
    p_expected_source_snapshot jsonb,
    p_worker_id text
) RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    affected integer;
BEGIN
    UPDATE public.jobs AS j
    SET freehire_compat_status = 'processing',
        freehire_compat_input_hash = p_expected_input_hash,
        freehire_compat_claimed_at = now(),
        freehire_compat_claimed_by = p_worker_id
    WHERE job_id = p_job_id
      AND provider = 'linkedin'
      AND (
          freehire_compat_status = 'pending'
          OR (freehire_compat_status = 'failed' AND COALESCE(freehire_compat_next_retry_at, '-infinity'::timestamptz) <= now())
          OR (freehire_compat_status = 'processing' AND COALESCE(freehire_compat_claimed_at, '-infinity'::timestamptz) < now() - interval '30 minutes')
      )
      AND (freehire_compat_input_hash IS NULL OR freehire_compat_input_hash = p_expected_input_hash)
      AND p_expected_source_snapshot <@ to_jsonb(j);
    GET DIAGNOSTICS affected = ROW_COUNT;
    RETURN affected = 1;
END;
$$;

CREATE OR REPLACE FUNCTION public.persist_freehire_compat_result(
    p_job_id text,
    p_expected_input_hash text,
    p_expected_source_snapshot jsonb,
    p_worker_id text,
    p_payload jsonb
) RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    affected integer;
BEGIN
    UPDATE public.jobs AS j
    SET freehire_category = CASE WHEN p_payload ? 'freehire_category' THEN p_payload->>'freehire_category' ELSE freehire_category END,
        freehire_seniority = CASE WHEN p_payload ? 'freehire_seniority' THEN p_payload->>'freehire_seniority' ELSE freehire_seniority END,
        is_remote = CASE WHEN p_payload ? 'is_remote' THEN (p_payload->>'is_remote')::boolean ELSE is_remote END,
        freehire_remote_evidence = CASE WHEN p_payload ? 'freehire_remote_evidence' THEN p_payload->'freehire_remote_evidence' ELSE freehire_remote_evidence END,
        freehire_compat_status = p_payload->>'freehire_compat_status',
        freehire_compat_import_hash = CASE WHEN p_payload ? 'freehire_compat_import_hash' THEN p_payload->>'freehire_compat_import_hash' ELSE freehire_compat_import_hash END,
        freehire_compat_model = p_payload->>'freehire_compat_model',
        freehire_compat_prompt_version = p_payload->>'freehire_compat_prompt_version',
        freehire_compat_schema_version = p_payload->>'freehire_compat_schema_version',
        freehire_compat_confidence = CASE WHEN p_payload ? 'freehire_compat_confidence' THEN (p_payload->>'freehire_compat_confidence')::numeric ELSE freehire_compat_confidence END,
        freehire_compat_classified_at = CASE WHEN p_payload ? 'freehire_compat_classified_at' THEN (p_payload->>'freehire_compat_classified_at')::timestamptz ELSE freehire_compat_classified_at END,
        freehire_compat_error = p_payload->>'freehire_compat_error',
        freehire_compat_attempts = (p_payload->>'freehire_compat_attempts')::integer,
        freehire_compat_claimed_at = NULL,
        freehire_compat_claimed_by = NULL,
        freehire_compat_next_retry_at = CASE WHEN p_payload ? 'freehire_compat_next_retry_at' AND p_payload->>'freehire_compat_next_retry_at' IS NOT NULL THEN (p_payload->>'freehire_compat_next_retry_at')::timestamptz ELSE NULL END,
        freehire_compat_provenance = p_payload->'freehire_compat_provenance'
    WHERE job_id = p_job_id
      AND freehire_compat_status = 'processing'
      AND freehire_compat_input_hash = p_expected_input_hash
      AND p_expected_source_snapshot <@ to_jsonb(j)
      AND freehire_compat_claimed_by = p_worker_id
      AND freehire_compat_claimed_at >= now() - interval '30 minutes';
    GET DIAGNOSTICS affected = ROW_COUNT;
    RETURN affected = 1;
END;
$$;
CREATE OR REPLACE FUNCTION public.calculate_listing_posting_waves(instances jsonb)
RETURNS TABLE(listing_instances jsonb, posting_wave_count integer, repost_count integer)
LANGUAGE sql
IMMUTABLE
SET search_path = pg_catalog, public
AS $$
WITH RECURSIVE source AS (
    SELECT
        ordinality::integer AS node_id,
        instance,
        NULLIF(
            btrim(regexp_replace(
                regexp_replace(
                    regexp_replace(lower(COALESCE(instance->>'location', '')), '[-/]', ' ', 'g'),
                    '[[:punct:]]', '', 'g'
                ),
                '\s+', ' ', 'g'
            )),
            ''
        ) AS normalized_location,
        CASE
            WHEN COALESCE(instance->>'posted_at', '') ~ '^\d{4}-\d{2}-\d{2}'
            THEN substring(instance->>'posted_at' FROM 1 FOR 10)
        END AS posted_date,
        NULLIF(instance->>'scrape_run_id', '') AS scrape_run_id,
        CASE
            WHEN COALESCE(instance->>'scraped_at', '') ~ '^\d{4}-\d{2}-\d{2}'
            THEN substring(instance->>'scraped_at' FROM 1 FOR 10)
        END AS scraped_date
    FROM jsonb_array_elements(COALESCE(instances, '[]'::jsonb)) WITH ORDINALITY values(instance, ordinality)
), edges AS (
    SELECT left_source.node_id AS left_id, right_source.node_id AS right_id
    FROM source left_source
    JOIN source right_source
      ON left_source.node_id <> right_source.node_id
     AND left_source.normalized_location IS NOT DISTINCT FROM right_source.normalized_location
     AND (
        left_source.normalized_location IS NULL
        OR (left_source.posted_date IS NOT NULL AND left_source.posted_date = right_source.posted_date)
        OR (left_source.scrape_run_id IS NOT NULL AND left_source.scrape_run_id = right_source.scrape_run_id)
        OR (
            left_source.posted_date IS NULL
            AND right_source.posted_date IS NULL
            AND left_source.scrape_run_id IS NULL
            AND right_source.scrape_run_id IS NULL
            AND (
                (left_source.scraped_date IS NOT NULL AND left_source.scraped_date = right_source.scraped_date)
                OR (left_source.scraped_date IS NULL AND right_source.scraped_date IS NULL)
            )
        )
     )
), reach(node_id, root_id) AS (
    SELECT node_id, node_id FROM source
    UNION
    SELECT edges.right_id, reach.root_id
    FROM reach
    JOIN edges ON edges.left_id = reach.node_id
), components AS (
    SELECT node_id, min(root_id) AS component_id
    FROM reach
    GROUP BY node_id
), component_values AS (
    SELECT
        components.component_id,
        min(CASE
            WHEN source.posted_date IS NOT NULL THEN source.posted_date
            WHEN source.instance->>'scraped_at' IS NOT NULL THEN source.instance->>'scraped_at'
            WHEN source.scrape_run_id IS NOT NULL THEN source.scrape_run_id
            ELSE '9999-12-31'
        END) AS component_sort,
        min(CASE
            WHEN source.normalized_location IS NULL THEN 'unknown_location'
            WHEN source.posted_date IS NOT NULL THEN 'posted:' || source.posted_date
            WHEN source.scrape_run_id IS NOT NULL THEN 'scrape_run:' || source.scrape_run_id
            WHEN source.scraped_date IS NOT NULL THEN 'scrape_date:' || source.scraped_date
            ELSE 'unknown'
        END) AS component_key
    FROM components
    JOIN source USING (node_id)
    GROUP BY components.component_id
), location_values AS (
    SELECT normalized_location, min(node_id) AS location_sort
    FROM source
    GROUP BY normalized_location
), ranked AS (
    SELECT
        source.*,
        components.component_id,
        dense_rank() OVER (
            PARTITION BY source.normalized_location
            ORDER BY component_values.component_sort, components.component_id
        )::integer AS wave_index,
        row_number() OVER (PARTITION BY components.component_id ORDER BY source.node_id)::integer AS member_index,
        dense_rank() OVER (
            ORDER BY location_values.location_sort
        )::integer AS location_index
    FROM source
    JOIN components USING (node_id)
    JOIN component_values USING (component_id)
    JOIN location_values ON location_values.normalized_location IS NOT DISTINCT FROM source.normalized_location
), annotated AS (
    SELECT
        ranked.node_id,
        jsonb_set(
            jsonb_set(
                jsonb_set(
                    CASE
                        WHEN ranked.normalized_location IS NULL THEN ranked.instance - 'normalized_location'
                        ELSE jsonb_set(
                            ranked.instance,
                            '{normalized_location}',
                            to_jsonb(ranked.normalized_location),
                            true
                        )
                    END,
                    '{posting_wave_key}',
                    to_jsonb(COALESCE(ranked.normalized_location, '') || '|' || component_values.component_key),
                    true
                ),
                '{posting_wave_index}',
                to_jsonb(ranked.wave_index),
                true
            ),
            '{variant_type}',
            to_jsonb(CASE
                WHEN ranked.member_index > 1 THEN 'simultaneous_variant'
                WHEN ranked.wave_index > 1 THEN 'repost'
                WHEN ranked.location_index > 1 THEN 'location_variant'
                ELSE 'original'
            END),
            true
        ) AS instance,
        ranked.wave_index
    FROM ranked
    JOIN component_values USING (component_id)
), result AS (
    SELECT
        COALESCE(jsonb_agg(instance ORDER BY node_id), '[]'::jsonb) AS listing_instances,
        COALESCE(max(wave_index), 0)::integer AS posting_wave_count
    FROM annotated
)
SELECT
    result.listing_instances,
    result.posting_wave_count,
    GREATEST(result.posting_wave_count - 1, 0)::integer AS repost_count
FROM result;
$$;

REVOKE ALL ON FUNCTION public.calculate_listing_posting_waves(jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_listing_posting_waves(jsonb) TO service_role;

REVOKE ALL ON FUNCTION public.apply_linkedin_relist_projection(text, text, uuid, date, timestamptz, jsonb, jsonb, timestamptz, jsonb, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.apply_same_id_relist_repair(text, jsonb, timestamptz, jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.apply_freehire_compat_metadata(text, jsonb, jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.claim_freehire_compat_job(text, text, jsonb, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.persist_freehire_compat_result(text, text, jsonb, text, jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_linkedin_relist_projection(text, text, uuid, date, timestamptz, jsonb, jsonb, timestamptz, jsonb, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_same_id_relist_repair(text, jsonb, timestamptz, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_freehire_compat_metadata(text, jsonb, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_freehire_compat_job(text, text, jsonb, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.persist_freehire_compat_result(text, text, jsonb, text, jsonb) TO service_role;



-- --- Base Resume Table ---
-- Stores the parsed resume JSON data securely in the database.
-- This avoids committing sensitive resume files to the public repository.
CREATE TABLE IF NOT EXISTS "public"."base_resume" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "resume_data" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."base_resume" OWNER TO "postgres";

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.base_resume'::regclass AND contype = 'p') THEN
        ALTER TABLE ONLY "public"."base_resume" ADD CONSTRAINT "base_resume_pkey" PRIMARY KEY ("id");
    END IF;
END $$;

-- Auto-update the updated_at column on changes
-- NOTE: Cannot reuse update_last_updated_column() because it references
-- "last_updated" which doesn't exist on base_resume (which uses "updated_at").
CREATE OR REPLACE FUNCTION "public"."update_base_resume_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
   NEW.updated_at = now();
   RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."update_base_resume_updated_at_column"() OWNER TO "postgres";

CREATE OR REPLACE TRIGGER "update_base_resume_updated_at"
    BEFORE UPDATE ON "public"."base_resume"
    FOR EACH ROW EXECUTE FUNCTION "public"."update_base_resume_updated_at_column"();

ALTER TABLE "public"."base_resume" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."base_resume" TO "anon";
GRANT ALL ON TABLE "public"."base_resume" TO "authenticated";
GRANT ALL ON TABLE "public"."base_resume" TO "service_role";

CREATE OR REPLACE FUNCTION "public"."replace_base_resume"("p_resume_data" jsonb) RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
BEGIN
    IF p_resume_data IS NULL OR jsonb_typeof(p_resume_data) <> 'object' OR p_resume_data = '{}'::jsonb THEN
        RAISE EXCEPTION 'resume payload must be a non-empty JSON object';
    END IF;
    DELETE FROM public.base_resume;
    INSERT INTO public.base_resume (resume_data) VALUES (p_resume_data);
    RETURN true;
END;
$$;
REVOKE ALL ON FUNCTION "public"."replace_base_resume"(jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION "public"."replace_base_resume"(jsonb) TO service_role;

-- --- Storage Setup ---
-- Create the resumes storage bucket for uploading the original resume PDF
INSERT INTO storage.buckets (id, name, public)
VALUES ('resumes', 'resumes', false)
ON CONFLICT (id) DO NOTHING;

-- Create the personalized_resumes storage bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public) 
VALUES ('personalized_resumes', 'personalized_resumes', false)
ON CONFLICT (id) DO NOTHING;

COMMIT;
